In [127]:
import pandas as pd
import math as m

In [128]:
import numpy as np

In [129]:
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [130]:
%matplotlib inline


In [131]:
#X= np.random.rand(10,2)
#X1 = np.random.rand(5,2)

In [132]:
# print(X)
# print(X1)

In [133]:
# X[5:10, :] = X1

In [134]:
# print(X)

In [135]:
data=pd.read_csv("kmeansdataset.csv")

In [136]:
print(data)

     a    b
0  1.2  7.1
1  5.4  9.4
2  9.6  4.8
3  1.6  2.9
4  8.4  3.7
5  7.4  8.4
6  8.4  7.1
7  3.7  5.6
8  6.3  4.4
9  1.9  6.7


In [1]:
x1 = data['a'].values

NameError: name 'data' is not defined

In [138]:
print(x1)

[1.2 5.4 9.6 1.6 8.4 7.4 8.4 3.7 6.3 1.9]


In [139]:
x2=data['b'].values

In [140]:
print(x2)

[7.1 9.4 4.8 2.9 3.7 8.4 7.1 5.6 4.4 6.7]


In [141]:
c = np.array(list(zip(x1,x2)))

In [142]:
print(c)

[[1.2 7.1]
 [5.4 9.4]
 [9.6 4.8]
 [1.6 2.9]
 [8.4 3.7]
 [7.4 8.4]
 [8.4 7.1]
 [3.7 5.6]
 [6.3 4.4]
 [1.9 6.7]]


In [143]:
c1 = [6.2,6.6,6.5]

In [144]:
c2 = [3.2,3.7,3.0]

In [145]:
centroid= np.array(list(zip(c1,c2)))

In [146]:
print(centroid)

[[6.2 3.2]
 [6.6 3.7]
 [6.5 3. ]]


In [147]:
for i in c:
    for j in centroid:
        val=np.linalg.norm(j-i)
        print(val)
    print('\n')

6.341135544995075
6.381222453417526
6.700746227100382


6.251399843235114
5.82494635168428
6.493843238021689


3.7576588456111866
3.195309061734091
3.584689665786984


4.6097722286464435
5.063595560468865
4.901020301937139


2.2561028345356955
1.8000000000000007
2.024845673131659


5.336665625650534
4.767598976424087
5.474486277268398


4.477722635447622
3.8470768123342687
4.518849411078001


3.465544690232691
3.4669871646719423
3.8209946349085597


1.2041594578792296
0.761577310586391
1.4142135623730956


5.5443665102516455
5.575840743780259
5.903388857258176


